# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/r3q/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/r3q

PRODUCT_COPY_FILES += \
    vendor/samsung/r3q/proprietary/vendor.img/bin/adsprpcd:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/bin/adsprpcd \
    vendor/samsung/r3q/proprietary/vendor.img/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/etc/perf/commonresourceconfigs.xml \
    vendor/samsung/r3q/proprietary/vendor.img/etc/perf/commonsysnodesconfigs.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/etc/perf/commonsysnodesconfigs.xml \
    vendor/samsung/r3q/proprietary/vendor.img/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/etc/perf/perfboostsconfig.xml \
    vendor/samsung/r3q/proprietary/vendor.img/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/etc/perf/perfconfigstore.xml \
    vendor/samsung/r3q/proprietary/vendor.img/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/etc/perf/targetconfig.xml \
    vendor/samsung/r3q/proprietary/vendor.img/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/etc/perf/targetresourceconfigs.xml \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libmmosal.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libmmosal.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libqti-perfd-client.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libqti-perfd.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libqti-perfd.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libqti-util.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libqti-util.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libqti-utils.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libqti-utils.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libscveCommon.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libscveCommon.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libscveCommon_stub.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libscveCommon_stub.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libscveObjectSegmentation.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libscveObjectSegmentation.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libscveObjectSegmentation_stub.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libscveObjectSegmentation_stub.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libscveObjectTracker.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libscveObjectTracker.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libscveObjectTracker_stub.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libscveObjectTracker_stub.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libwfdaac_vendor.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libwfdaac_vendor.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/libwvhidl.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/libwvhidl.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/rfsa/adsp/libscveObjectSegmentation_skel.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/rfsa/adsp/libscveObjectSegmentation_skel.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/rfsa/adsp/libscveT2T_skel.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/rfsa/adsp/libscveT2T_skel.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/vendor.qti.data.slm@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/vendor.qti.data.slm@1.0.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/vendor.qti.hardware.data.connection@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/vendor.qti.hardware.data.connection@1.0.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/vendor.qti.hardware.data.connection@1.1.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/vendor.qti.hardware.data.connection@1.1.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/vendor.qti.hardware.data.dynamicdds@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/vendor.qti.hardware.data.dynamicdds@1.0.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/vendor.qti.hardware.scve.objecttracker@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/vendor.qti.hardware.scve.objecttracker@1.0.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib/vendor.qti.hardware.scve.panorama@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib/vendor.qti.hardware.scve.panorama@1.0.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libmmosal.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libmmosal.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libqti-perfd-client.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libqti-perfd-client.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libqti-perfd.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libqti-perfd.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libqti-util.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libqti-util.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libqti-utils.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libqti-utils.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libscveCommon.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libscveCommon.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libscveCommon_stub.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libscveCommon_stub.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libscveObjectSegmentation.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libscveObjectSegmentation.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libscveObjectSegmentation_stub.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libscveObjectSegmentation_stub.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libscveObjectTracker.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libscveObjectTracker.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/libscveObjectTracker_stub.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/libscveObjectTracker_stub.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/vendor.qti.data.slm@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/vendor.qti.data.slm@1.0.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/vendor.qti.hardware.data.connection@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/vendor.qti.hardware.data.connection@1.0.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/vendor.qti.hardware.data.connection@1.1.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/vendor.qti.hardware.data.connection@1.1.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/vendor.qti.hardware.data.dynamicdds@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/vendor.qti.hardware.data.dynamicdds@1.0.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/vendor.qti.hardware.scve.objecttracker@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/vendor.qti.hardware.scve.objecttracker@1.0.so \
    vendor/samsung/r3q/proprietary/vendor.img/lib64/vendor.qti.hardware.scve.panorama@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/vendor.img/lib64/vendor.qti.hardware.scve.panorama@1.0.so
